{% set version = "0.15.1" %}

package:
  name: go-spr
  version: {{ version }}

source:
  url: https://github.com/ejoffe/spr/archive/v{{ version }}.tar.gz
  sha256: 6108ffe852f3eb62053f87a6a61d20f383fe10f4442396d6730e7f3c534c3f16

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses
  run:
    - git

test:
  commands:
    - 'spr 2>&1 | grep -q "No GitHub OAuth token found!"'  # [linux]
    - 'spr 2>&1 | grep -q "git error: fatal: not a git repository"'  # [osx or win]

about:
  home: https://github.com/ejoffe/spr
  license: MIT
  license_file:
    - LICENSE
    - license-files_amend/
    - license-files_reword/
    - license-files_spr/
  summary: Stacked Pull Requests on GitHub
  dev_url: https://github.com/ejoffe/spr

extra:
  recipe-maintainers:
    - danielnachun
