{% set version = "0.14.9" %}

package:
  name: go-spr
  version: {{ version }}

source:
  url: https://github.com/ejoffe/spr/archive/v{{ version }}.tar.gz
  sha256: 150a9ad1db8b6466e50c5d7d0dbc589a57b2b774eb8cf8d23598f5d75196873f

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses
  run:
    - git

test:
  commands:
    - 'spr 2>&1 | grep -q "No GitHub OAuth token found!"'  # [linux]
    - 'spr 2>&1 | grep -q "git error: fatal: not a git repository"'  # [osx or win]

about:
  home: https://github.com/ejoffe/spr
  license: MIT
  license_file:
    - LICENSE
    - license-files_amend/
    - license-files_reword/
    - license-files_spr/
  summary: Stacked Pull Requests on GitHub
  dev_url: https://github.com/ejoffe/spr

extra:
  recipe-maintainers:
    - danielnachun
