{% set version = "0.15.0" %}

package:
  name: go-spr
  version: {{ version }}

source:
  url: https://github.com/ejoffe/spr/archive/v{{ version }}.tar.gz
  sha256: 0cc0df7f18ea5f5ceed50ac5d9f76622315a69f06473e40673aaa09c9e4f4cb3

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses
  run:
    - git

test:
  commands:
    - 'spr 2>&1 | grep -q "No GitHub OAuth token found!"'  # [linux]
    - 'spr 2>&1 | grep -q "git error: fatal: not a git repository"'  # [osx or win]

about:
  home: https://github.com/ejoffe/spr
  license: MIT
  license_file:
    - LICENSE
    - license-files_amend/
    - license-files_reword/
    - license-files_spr/
  summary: Stacked Pull Requests on GitHub
  dev_url: https://github.com/ejoffe/spr

extra:
  recipe-maintainers:
    - danielnachun
