schema_version: 1

context:
  version: "0.17.1"

package:
  name: go-spr
  version: ${{ version }}

source:
  url: https://github.com/ejoffe/spr/archive/v${{ version }}.tar.gz
  sha256: 320f6c018a532fe261ce4e5f3094afc9f8898b878c15200f9b44f9596a6cb8f0

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses
  run:
    - git

tests:
  - script:
      - if: linux
        then: spr 2>&1 | grep -q "No GitHub OAuth token found!"
      - if: osx or win
        then: 'spr 2>&1 | grep -q "git error: fatal: not a git repository"'

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files_amend/
    - license-files_reword/
    - license-files_spr/
  summary: Stacked Pull Requests on GitHub
  homepage: https://github.com/ejoffe/spr
  repository: https://github.com/ejoffe/spr

extra:
  recipe-maintainers:
    - danielnachun
